CREATE TYPE academic_track_enum AS ENUM (
    'TERMINALE_SCIENCES_EXACTES',
    'MATHS_INFORMATIQUE',
    'MATHS_GESTION_COMPTABILITE',
    'SCIENCES_BIOTECHNOLOGIQUES',
    'TERMINALE_SCIENCES_EXPERIMENTALES',
    'MATHS_TECHNOLOGIQUES',
    'SCIENCES_ET_TECHNOLOGIES_DE_GESTION',
    'TERMINALE_SCIENCES_ECONOMIQUES',
    'SCIENCES_HUMAINES_ET_TECHNOLOGIQUES',
    'TERMINALE_SCIENCES_SOCIALES',
    'SCIENCES_ET_TECHNOLOGIES_INDUSTRIELLES',
    'TERMINALE_LANGUES_LITTERATURE',
    'TERMINALE_ARTS_LITTERAIRES'
);

CREATE TYPE academic_subject_enum AS ENUM ('MATHEMATICS', 'FINANCE_MATHEMATICS');

CREATE TYPE country_enum AS ENUM ('MALI');

-- Now, create the table
CREATE TABLE academic_exam_document (
    id SERIAL PRIMARY KEY,
    upload_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    exam_date DATE NOT NULL,
    file_path TEXT NOT NULL,
    correction_file_path TEXT,
    track academic_track_enum [] NOT NULL,
    country country_enum NOT NULL,
    subject academic_subject_enum NOT NULL
);

-- TSE - TERMINALE_SCIENCES_EXACTES
-- MTI - MATHS_INFORMATIQUE
-- MTGC - MATHS_GESTION_COMPTABILITE
-- SBT - SCIENCES_BIOTECHNOLOGIQUES
-- TSEXP - TERMINALE_SCIENCES_EXPERIMENTALES
-- MTE - MATHS_TECHNOLOGIQUES
-- STG - SCIENCES_ET_TECHNOLOGIES_DE_GESTION
-- TSECO - TERMINALE_SCIENCES_ECONOMIQUES
-- SHT - SCIENCES_HUMAINES_ET_TECHNOLOGIQUES
-- TSS - TERMINALE_SCIENCES_SOCIALES
-- STI - SCIENCES_ET_TECHNOLOGIES_INDUSTRIELLES
-- TLL - TERMINALE_LANGUES_LITTERATURE
-- TAL - TERMINALE_ARTS_LITTERAIRES
